### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by DarK-VEnOM-16** [boradesanket13/Tune-It-A-Music-player#1]
@boradesanket13 I would like to add Readme file for this project.

**Comment by NihalAhmadKhan** [comment]
I want to contribute in this issue

**Comment by Vaibhavpandey1709** [comment]
I want to contribute in this issue

**Comment by boradesanket13** [comment]
[DarK-VEnOM-16](https://github.com/DarK-VEnOM-16)
Go ahead!

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 Can I work on this?
