### ISSUE TITLE
Pause Feature for side menu bar

### ISSUE THREAD

**Issue by DarK-VEnOM-16** [boradesanket13/Tune-It-A-Music-player#2]
@boradesanket13 
Currently only play option is available in side-menu bar, it would be better If a person can also pause from it.

Please assign me this issue.

**Comment by Gaurav945572** [comment]
Please assign it to me.

**Comment by Tushar98644** [comment]
I would like to take up the issue ...

**Comment by DarK-VEnOM-16** [comment]
@boradesanket13 I have made a PR with same name Can You please take a look.

**Comment by boradesanket13** [comment]
Great PR!🚀
