### ISSUE TITLE
Fetch data from spotify API

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Tune-It-A-Music-player#3]
Fetch data from spotify API
- Tell your approach and what you will contribute while asking to be assigned

**Comment by Abhijeet-2003** [comment]
Could you please elaborate on this, like what do we need to do with the fetched data?

**Comment by boradesanket13** [comment]
Fetch music artists, albums, and tracks and show them on a new pages. Create appropriate UI for the same.
I'm making this issue as BONUS issue. Will award extra points (upto 50) based on your work.
@Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
Sure, I'll start working on this. @boradesanket13

**Comment by Abhijeet-2003** [comment]
Hey @boradesanket13. Just wanted to let you know my progress till now.
I'm able to successfully fetch the necessary data using the API and am currently working on the UI part mostly.

**Comment by Abhijeet-2003** [comment]
Hey @boradesanket13. I've sent a pr #12  for this issue.
