### ISSUE TITLE
Fix artist's photos

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/Tune-It-A-Music-player#4]
Fix artist's photos. They look stretch in current version

**Comment by Shivam-jainn** [comment]
Hey , 
I am beginner and i think i can fix this . Please assign this to me .

Thank you

**Comment by shivamkgpian** [comment]
hey, i would to contribute to this

**Comment by Tushar98644** [comment]
I would like to contribute to it ....

**Comment by ankushj0801** [comment]
can you assign it to me please

**Comment by boradesanket13** [comment]
@shivamkgpian 
Go ahead! Contribute well🚀

Rest folks, thanks for your interest. we're assigning issues on a first come first serve basis. If @shivamkgpian isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another codepeak issue [here](https://github.com/boradesanket13?tab=repositories).
