### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by AyushTripathiIITP** [boradesanket13/Tune-It-A-Music-player#5]
I noticed that you website doesn't have a favicon i would like to add this please assign me this issue @boradesanket13

**Comment by ankushj0801** [comment]
I want to work on this please assign it to me

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀 @AyushTripathiIITP

**Comment by boradesanket13** [comment]
@ankushj0801  , thanks for your interest!

We're assigning issues on a first come first serve basis. If @AyushTripathiIITP  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another CODEPEAK issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by boradesanket13** [comment]
@ankushj0801  , thanks for your interest!

We're assigning issues on a first come first serve basis. If @AyushTripathiIITP  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by boradesanket13** [comment]
@AyushTripathiIITP Send design here before implementing in code

**Comment by AyushTripathiIITP** [comment]
![image](https://user-images.githubusercontent.com/101452500/206187884-3e6ce7fc-0e68-407f-92c6-a22f4888daf8.png)
does it look good

**Comment by AyushTripathiIITP** [comment]
@boradesanket13 does it look good
![image](https://user-images.githubusercontent.com/101452500/206188048-c84943dc-0d5d-47bb-887d-bd48fae77045.png)

**Comment by boradesanket13** [comment]
Yess! Go for the PR!
@AyushTripathiIITP
